import React from "react";

export default React.createContext({
  user: { id: null, firstName: "", lastName: "", photo: "" },
  setUser: () => {},
  secondaryUser: { id: null, firstName: "", lastName: "", photo: "" },
  setUserShare: () => {},
  comments: [],
  setComments: () => {},
  post: {
    id: null,
    userId: null,
    likeId: null,
    postSharedUserId: null,
    shareId: null,
    content: "",
    date: "",
    numberOfLikes: null,
    numberOfShares: null,
    numberOfComments: null,
    isMoreComments: false,
    comments:[{
      commentId: null,
      postId: null,
      userId: null,
      likeId: null,
      numberOfLikes: null,
      numberOfReplies: null,
      content: "",
      date: ""
    }]
  },
  setPost: () => {},
  isMoreComments: false,
  setStatusOfMoreComments: () => {},
  numberOfComments: null,
  setNumberOfComments: () => {},
  isHidenPost: false,
  setStatusOfHiddenPost: () => {},
  isReport: false,
  setStatusOfReport: () => {},
  isEdit: false,
  setStatusOfEdit: () => {},
  isSingle: false,
  setStatusOfSingle: () => {},
});
